import type { Metadata } from "next";
import Link from "next/link";
import { PublicShell } from "@/components/public/public-page";

export const metadata: Metadata = { title: "Support", description: "Get help with BasicUniformPOS." };

export default function SupportPage() {
  return <PublicShell><section className="mx-auto max-w-4xl px-5 py-16 sm:px-8 sm:py-24"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#0b8279]">Help when the store is moving</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.06em]">Support for your team</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#30413d]">Start with the demo for a safe tour, or contact us when you need help mapping a real store workflow.</p><div className="mt-12 grid gap-5 md:grid-cols-3"><article className="rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Try the demo</h2><p className="mt-3 leading-7 text-[#30413d]">Explore the register and manager flows with sample data. No account or payment required.</p><Link href="/demo" className="mt-5 inline-flex rounded-full bg-[#0b8279] px-4 py-2 font-semibold text-white">Open demo</Link></article><article className="rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Book a walkthrough</h2><p className="mt-3 leading-7 text-[#30413d]">Talk through size runs, purchasing, inventory, and reporting with the BUPOS team.</p><a href="mailto:hello@basicuniformpos.com?subject=BUPOS%20walkthrough" className="mt-5 inline-flex rounded-full bg-[#15201f] px-4 py-2 font-semibold text-white">Email us</a></article><article className="rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Migration questions</h2><p className="mt-3 leading-7 text-[#30413d]">Ask about your current register, exports, and a sensible transition plan.</p><a href="mailto:hello@basicuniformpos.com?subject=BUPOS%20migration" className="mt-5 inline-flex rounded-full border border-[#15201f]/20 px-4 py-2 font-semibold">Ask a question</a></article></div><p className="mt-10 text-sm text-[#52605d]">For urgent account access concerns, include your store name and a safe callback detail. Never send passwords, PINs, or payment credentials by email.</p></section></PublicShell>;
}
