-- Migration: Force Row Level Security on all org-scoped tables
-- FORCE ensures RLS policies apply even to the table owner role,
-- preventing accidental bypasses from app code running as the owner.

-- Core org-scoped tables
ALTER TABLE organizations FORCE ROW LEVEL SECURITY;
ALTER TABLE locations FORCE ROW LEVEL SECURITY;
ALTER TABLE employees FORCE ROW LEVEL SECURITY;
ALTER TABLE categories FORCE ROW LEVEL SECURITY;
ALTER TABLE modifier_groups FORCE ROW LEVEL SECURITY;
ALTER TABLE modifiers FORCE ROW LEVEL SECURITY;
ALTER TABLE products FORCE ROW LEVEL SECURITY;
ALTER TABLE product_variants FORCE ROW LEVEL SECURITY;
ALTER TABLE inventory_levels FORCE ROW LEVEL SECURITY;
ALTER TABLE customers FORCE ROW LEVEL SECURITY;
ALTER TABLE transactions FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
ALTER TABLE gift_cards FORCE ROW LEVEL SECURITY;
ALTER TABLE store_credit_ledger FORCE ROW LEVEL SECURITY;
ALTER TABLE behavior_flags FORCE ROW LEVEL SECURITY;
ALTER TABLE layaways FORCE ROW LEVEL SECURITY;
ALTER TABLE stocktakes FORCE ROW LEVEL SECURITY;
ALTER TABLE transfers FORCE ROW LEVEL SECURITY;
ALTER TABLE time_clock_entries FORCE ROW LEVEL SECURITY;
ALTER TABLE promo_codes FORCE ROW LEVEL SECURITY;
ALTER TABLE returns FORCE ROW LEVEL SECURITY;

-- Child tables (secured via FK joins in 009_rls_policies.sql)
ALTER TABLE transaction_tenders FORCE ROW LEVEL SECURITY;
ALTER TABLE transaction_events FORCE ROW LEVEL SECURITY;
ALTER TABLE transaction_exceptions FORCE ROW LEVEL SECURITY;
ALTER TABLE pay_in_outs FORCE ROW LEVEL SECURITY;
ALTER TABLE auth_credentials FORCE ROW LEVEL SECURITY;
ALTER TABLE sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE register_sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE shifts FORCE ROW LEVEL SECURITY;
ALTER TABLE inventory_adjustments FORCE ROW LEVEL SECURITY;
ALTER TABLE gift_card_transactions FORCE ROW LEVEL SECURITY;
ALTER TABLE layaway_payments FORCE ROW LEVEL SECURITY;
ALTER TABLE stocktake_lines FORCE ROW LEVEL SECURITY;
ALTER TABLE transfer_lines FORCE ROW LEVEL SECURITY;
ALTER TABLE promo_redemptions FORCE ROW LEVEL SECURITY;
ALTER TABLE product_modifier_groups FORCE ROW LEVEL SECURITY;
ALTER TABLE register_session_exceptions FORCE ROW LEVEL SECURITY;
ALTER TABLE return_lines FORCE ROW LEVEL SECURITY;
