/**
 * Sales tax rate lookup by city/state.
 * Rates are combined district + city + county + state rates.
 * Updated as of 2026. Verify before use — rates change quarterly.
 */

export interface TaxRateEntry {
  city: string;
  state: string;
  rate: number;
  description?: string;
}

export const STATE_DEFAULT_RATES: Record<string, number> = {
  AL: 0.04, AK: 0.00, AZ: 0.056, AR: 0.065, CA: 0.0725,
  CO: 0.029, CT: 0.0635, DE: 0.00, FL: 0.06, GA: 0.04,
  HI: 0.04, ID: 0.06, IL: 0.0625, IN: 0.07, IA: 0.06,
  KS: 0.065, KY: 0.06, LA: 0.0445, ME: 0.055, MD: 0.06,
  MA: 0.0625, MI: 0.06, MN: 0.06875, MS: 0.07, MO: 0.04225,
  MT: 0.00, NE: 0.055, NV: 0.0685, NH: 0.00, NJ: 0.06625,
  NM: 0.05125, NY: 0.08, NC: 0.0475, ND: 0.05, OH: 0.0575,
  OK: 0.045, OR: 0.00, PA: 0.06, RI: 0.07, SC: 0.06,
  SD: 0.045, TN: 0.07, TX: 0.0625, UT: 0.0485, VT: 0.06,
  VA: 0.053, WA: 0.065, WV: 0.06, WI: 0.05, WY: 0.04,
  DC: 0.06,
};

export const US_STATES = [
  { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" }, { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" }, { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" }, { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" }, { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" }, { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" }, { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" }, { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" }, { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" }, { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" }, { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" }, { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" }, { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" }, { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" }, { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" }, { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" }, { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" }, { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" }, { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" }, { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" }, { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" },
  { code: "DC", name: "Washington DC" },
];

const CA_TAX_RATES: TaxRateEntry[] = [
  { city: "Los Angeles",       state: "CA", rate: 0.0975, description: "LA County + City" },
  { city: "Long Beach",        state: "CA", rate: 0.1025, description: "LA County + Long Beach" },
  { city: "Pasadena",         state: "CA", rate: 0.1025, description: "LA County + Pasadena" },
  { city: "Burbank",           state: "CA", rate: 0.1025, description: "LA County + Burbank" },
  { city: "Glendale",          state: "CA", rate: 0.1025, description: "LA County + Glendale" },
  { city: "Santa Clarita",    state: "CA", rate: 0.0975, description: "LA County" },
  { city: "Lancaster",         state: "CA", rate: 0.0975, description: "LA County" },
  { city: "Palmdale",         state: "CA", rate: 0.0975, description: "LA County" },
  { city: "Malibu",           state: "CA", rate: 0.0975, description: "LA County + Malibu" },
  { city: "West Hollywood",   state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Santa Monica",     state: "CA", rate: 0.1025, description: "LA County + Santa Monica" },
  { city: "Inglewood",        state: "CA", rate: 0.1025, description: "LA County + Inglewood" },
  { city: "Compton",          state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Torrance",         state: "CA", rate: 0.1025, description: "LA County + Torrance" },
  { city: "El Segundo",       state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Manhattan Beach",  state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Hermosa Beach",    state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Redondo Beach",    state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Hawthorne",        state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Culver City",      state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Beverly Hills",    state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Westlake Village", state: "CA", rate: 0.0975, description: "Ventura County" },
  { city: "Thousand Oaks",    state: "CA", rate: 0.0975, description: "Ventura County" },
  { city: "Oxnard",           state: "CA", rate: 0.0975, description: "Ventura County + Oxnard" },
  { city: "Ventura",          state: "CA", rate: 0.0975, description: "Ventura County" },
  { city: "Simi Valley",      state: "CA", rate: 0.0975, description: "Ventura County" },
  { city: "Anaheim",          state: "CA", rate: 0.0775, description: "OC + Anaheim" },
  { city: "Santa Ana",        state: "CA", rate: 0.0775, description: "OC + Santa Ana" },
  { city: "Irvine",           state: "CA", rate: 0.0775, description: "OC + Irvine" },
  { city: "Huntington Beach", state: "CA", rate: 0.0775, description: "OC + Huntington Beach" },
  { city: "Newport Beach",    state: "CA", rate: 0.0775, description: "OC + Newport Beach" },
  { city: "Costa Mesa",       state: "CA", rate: 0.0825, description: "OC + Costa Mesa" },
  { city: "Fullerton",        state: "CA", rate: 0.0775, description: "OC + Fullerton" },
  { city: "Garden Grove",      state: "CA", rate: 0.0775, description: "OC + Garden Grove" },
  { city: "Orange",           state: "CA", rate: 0.0775, description: "OC + Orange" },
  { city: "Tustin",           state: "CA", rate: 0.0775, description: "OC + Tustin" },
  { city: "Mission Viejo",    state: "CA", rate: 0.0775, description: "OC + Mission Viejo" },
  { city: "Laguna Beach",     state: "CA", rate: 0.0775, description: "OC" },
  { city: "San Clemente",     state: "CA", rate: 0.0775, description: "OC" },
  { city: "Dana Point",       state: "CA", rate: 0.0775, description: "OC" },
  { city: "San Bernardino",   state: "CA", rate: 0.0875, description: "San Bernardino County" },
  { city: "Riverside",        state: "CA", rate: 0.0875, description: "Riverside County" },
  { city: "Fontana",          state: "CA", rate: 0.0875, description: "San Bernardino County" },
  { city: "Rancho Cucamonga", state: "CA", rate: 0.0875, description: "San Bernardino County" },
  { city: "Ontario",          state: "CA", rate: 0.0875, description: "San Bernardino County + Ontario" },
  { city: "Victorville",       state: "CA", rate: 0.0875, description: "San Bernardino County" },
  { city: "Corona",          state: "CA", rate: 0.0875, description: "Riverside County" },
  { city: "Murrieta",         state: "CA", rate: 0.0875, description: "Riverside County" },
  { city: "Temecula",         state: "CA", rate: 0.0875, description: "Riverside County" },
  { city: "San Diego",        state: "CA", rate: 0.0775, description: "San Diego County" },
  { city: "Chula Vista",       state: "CA", rate: 0.0775, description: "San Diego County" },
  { city: "Carlsbad",         state: "CA", rate: 0.0775, description: "San Diego County" },
  { city: "Encinitas",        state: "CA", rate: 0.0775, description: "San Diego County" },
  { city: "Escondido",        state: "CA", rate: 0.0775, description: "San Diego County" },
  { city: "Oceanside",        state: "CA", rate: 0.0775, description: "San Diego County" },
  { city: "El Cajon",          state: "CA", rate: 0.0775, description: "San Diego County" },
  { city: "San Francisco",     state: "CA", rate: 0.0875, description: "SF County + City" },
  { city: "Oakland",          state: "CA", rate: 0.1025, description: "Alameda County + Oakland" },
  { city: "Berkeley",         state: "CA", rate: 0.1025, description: "Alameda County + Berkeley" },
  { city: "Alameda",          state: "CA", rate: 0.1025, description: "Alameda County" },
  { city: "Fremont",          state: "CA", rate: 0.1025, description: "Alameda County" },
  { city: "Hayward",          state: "CA", rate: 0.1025, description: "Alameda County" },
  { city: "Richmond",         state: "CA", rate: 0.1025, description: "Contra Costa County" },
  { city: "Walnut Creek",     state: "CA", rate: 0.1025, description: "Contra Costa County" },
  { city: "Concord",          state: "CA", rate: 0.1025, description: "Contra Costa County" },
  { city: "San Jose",         state: "CA", rate: 0.0925, description: "Santa Clara County + San Jose" },
  { city: "Sunnyvale",        state: "CA", rate: 0.0925, description: "Santa Clara County" },
  { city: "Santa Clara",      state: "CA", rate: 0.0925, description: "Santa Clara County" },
  { city: "Mountain View",     state: "CA", rate: 0.0925, description: "Santa Clara County" },
  { city: "Palo Alto",         state: "CA", rate: 0.0925, description: "Santa Clara County" },
  { city: "Cupertino",         state: "CA", rate: 0.0925, description: "Santa Clara County" },
  { city: "Menlo Park",        state: "CA", rate: 0.0925, description: "San Mateo County" },
  { city: "Redwood City",      state: "CA", rate: 0.0925, description: "San Mateo County" },
  { city: "Daly City",         state: "CA", rate: 0.0925, description: "San Mateo County" },
  { city: "San Mateo",         state: "CA", rate: 0.0925, description: "San Mateo County" },
  { city: "Petaluma",         state: "CA", rate: 0.0925, description: "Sonoma County" },
  { city: "Santa Rosa",        state: "CA", rate: 0.0925, description: "Sonoma County" },
  { city: "Napa",             state: "CA", rate: 0.0875, description: "Napa County" },
  { city: "Vallejo",          state: "CA", rate: 0.0875, description: "Solano County" },
  { city: "Fairfield",         state: "CA", rate: 0.0875, description: "Solano County" },
  { city: "Fresno",           state: "CA", rate: 0.0875, description: "Fresno County" },
  { city: "Clovis",           state: "CA", rate: 0.0875, description: "Fresno County" },
  { city: "Modesto",          state: "CA", rate: 0.0875, description: "Stanislaus County" },
  { city: "Turlock",          state: "CA", rate: 0.0875, description: "Stanislaus County" },
  { city: "Stockton",         state: "CA", rate: 0.0925, description: "San Joaquin County" },
  { city: "Tracy",            state: "CA", rate: 0.0925, description: "San Joaquin County" },
  { city: "Manteca",          state: "CA", rate: 0.0925, description: "San Joaquin County" },
  { city: "Bakersfield",      state: "CA", rate: 0.0775, description: "Kern County" },
  { city: "Visalia",          state: "CA", rate: 0.0775, description: "Tulare County" },
  { city: "Santa Barbara",    state: "CA", rate: 0.0875, description: "Santa Barbara County" },
  { city: "Santa Maria",       state: "CA", rate: 0.0875, description: "Santa Barbara County" },
  { city: "San Luis Obispo",  state: "CA", rate: 0.0825, description: "SLO County" },
  { city: "Monterey",         state: "CA", rate: 0.0925, description: "Monterey County" },
  { city: "Salinas",          state: "CA", rate: 0.0925, description: "Monterey County" },
  { city: "Watsonville",       state: "CA", rate: 0.0925, description: "Santa Cruz County" },
  { city: "Santa Cruz",        state: "CA", rate: 0.0925, description: "Santa Cruz County" },
  { city: "Palm Springs",      state: "CA", rate: 0.0875, description: "Riverside County" },
  { city: "Rancho Mirage",    state: "CA", rate: 0.0875, description: "Riverside County" },
  { city: "La Quinta",        state: "CA", rate: 0.0875, description: "Riverside County" },
  { city: "Chino",            state: "CA", rate: 0.0875, description: "San Bernardino County" },
  { city: "Pomona",           state: "CA", rate: 0.0975, description: "LA County + Pomona" },
  { city: "West Covina",       state: "CA", rate: 0.0975, description: "LA County + West Covina" },
  { city: "Downey",           state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Norwalk",          state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Bellflower",        state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Lakewood",         state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Carson",           state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Arcadia",          state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Monrovia",         state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Azusa",            state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Covina",           state: "CA", rate: 0.1025, description: "LA County" },
  { city: "San Dimas",        state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Glendora",         state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Diamond Bar",      state: "CA", rate: 0.1025, description: "LA County" },
  { city: "Walnut",           state: "CA", rate: 0.1025, description: "LA County" },
];

const OTHER_CITY_RATES: TaxRateEntry[] = [
  { city: "Austin",           state: "TX", rate: 0.0825, description: "Travis County + Austin" },
  { city: "Houston",          state: "TX", rate: 0.0825, description: "Harris County + Houston" },
  { city: "Dallas",           state: "TX", rate: 0.0825, description: "Dallas County + Dallas" },
  { city: "San Antonio",       state: "TX", rate: 0.0825, description: "Bexar County + SA" },
  { city: "Fort Worth",        state: "TX", rate: 0.0825, description: "Tarrant County + FW" },
  { city: "Plano",            state: "TX", rate: 0.0825, description: "Collin County" },
  { city: "Las Vegas",         state: "NV", rate: 0.0825, description: "Clark County + LV" },
  { city: "Reno",             state: "NV", rate: 0.0825, description: "Washoe County + Reno" },
  { city: "Henderson",         state: "NV", rate: 0.0825, description: "Clark County" },
  { city: "Phoenix",          state: "AZ", rate: 0.084,  description: "Maricopa County" },
  { city: "Scottsdale",        state: "AZ", rate: 0.084,  description: "Maricopa County" },
  { city: "Tucson",           state: "AZ", rate: 0.081,  description: "Pima County" },
  { city: "Mesa",             state: "AZ", rate: 0.084,  description: "Maricopa County" },
  { city: "Chandler",          state: "AZ", rate: 0.084,  description: "Maricopa County" },
  { city: "Gilbert",           state: "AZ", rate: 0.084,  description: "Maricopa County" },
  { city: "Miami",            state: "FL", rate: 0.07,   description: "Miami-Dade County" },
  { city: "Orlando",           state: "FL", rate: 0.065,  description: "Orange County" },
  { city: "Tampa",            state: "FL", rate: 0.075,  description: "Hillsborough County" },
  { city: "Jacksonville",     state: "FL", rate: 0.07,   description: "Duval County" },
  { city: "Fort Lauderdale",  state: "FL", rate: 0.07,   description: "Broward County" },
  { city: "Seattle",          state: "WA", rate: 0.1025, description: "King County + Seattle" },
  { city: "Tacoma",           state: "WA", rate: 0.1025, description: "Pierce County" },
  { city: "Spokane",          state: "WA", rate: 0.095,  description: "Spokane County" },
  { city: "Portland",          state: "OR", rate: 0.00,   description: "No state sales tax" },
  { city: "Denver",           state: "CO", rate: 0.0877, description: "Denver + state" },
  { city: "Boulder",           state: "CO", rate: 0.0877, description: "Boulder + state" },
  { city: "Colorado Springs",  state: "CO", rate: 0.0822, description: "El Paso County" },
  { city: "New York",         state: "NY", rate: 0.08875, description: "NYC (state + city + MCTD)" },
  { city: "Buffalo",           state: "NY", rate: 0.08,   description: "Erie County" },
  { city: "Chicago",           state: "IL", rate: 0.1025, description: "Cook County + Chicago" },
  { city: "Detroit",           state: "MI", rate: 0.06,   description: "Detroit + state" },
  { city: "Columbus",          state: "OH", rate: 0.0725, description: "Franklin County" },
  { city: "Cleveland",         state: "OH", rate: 0.08,   description: "Cuyahoga County" },
  { city: "Atlanta",           state: "GA", rate: 0.0889, description: "Fulton County + Atlanta" },
  { city: "Savannah",          state: "GA", rate: 0.07,   description: "Chatham County" },
  { city: "Charlotte",        state: "NC", rate: 0.0725, description: "Mecklenburg County" },
  { city: "Raleigh",           state: "NC", rate: 0.0725, description: "Wake County" },
  { city: "Virginia Beach",   state: "VA", rate: 0.06,   description: "Virginia Beach" },
  { city: "Alexandria",       state: "VA", rate: 0.06,   description: "Alexandria" },
  { city: "Arlington",         state: "VA", rate: 0.06,   description: "Arlington County" },
  { city: "Philadelphia",     state: "PA", rate: 0.08,   description: "Philadelphia + PA" },
  { city: "Pittsburgh",        state: "PA", rate: 0.07,   description: "Allegheny County" },
  { city: "Boston",           state: "MA", rate: 0.0625, description: "Boston + state" },
  { city: "Honolulu",          state: "HI", rate: 0.04,   description: "HI state GET only" },
];

const ALL_RATES: TaxRateEntry[] = [...CA_TAX_RATES, ...OTHER_CITY_RATES];

export function getCitiesForState(state: string): string[] {
  const cities = ALL_RATES
    .filter((r) => r.state === state)
    .map((r) => r.city);
  return [...new Set(cities)].sort();
}

export function getTaxRate(city: string, state: string): number {
  const match = ALL_RATES.find(
    (r) => r.city.toLowerCase() === city.toLowerCase() && r.state === state,
  );
  if (match) return match.rate;
  return STATE_DEFAULT_RATES[state] ?? 0;
}

export function getTaxEntry(city: string, state: string): TaxRateEntry | null {
  return (
    ALL_RATES.find(
      (r) => r.city.toLowerCase() === city.toLowerCase() && r.state === state,
    ) ?? null
  );
}
